-- ACA VAMOS PONIENDO LOS INSERTS EN LA BASE DE PRUEBA

-- AULAS
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (1,"ornare.","Ap #391-9405 Dolor Avenue",19,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (2,"ac","910-2317 Lectus Av.",31,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (3,"sit","Ap #398-4195 At, Street",56,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (4,"a,","2680 Non, St.",10,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (5,"lacinia","1179 Turpis. Av.",35,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (6,"nec,","7228 Primis Ave",25,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (7,"vulputate","P.O. Box 201, 3560 Id St.",52,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (8,"Nulla","P.O. Box 809, 1626 Arcu. St.",26,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (9,"nunc","480-4751 Eleifend. Av.",46,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (10,"Proin","6875 Vulputate, Av.",22,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (11,"congue.","7176 Auctor Avenue",45,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (12,"Phasellus","610-8789 Ut Street",16,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (13,"quam.","2731 Eu Road",46,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (14,"auctor","Ap #447-7256 Sem Av.",22,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (15,"pede.","5958 Consectetuer Av.",30,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (16,"mattis","Ap #870-8456 Eu Ave",37,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (17,"nec","P.O. Box 376, 4983 Nec Ave",58,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (18,"ornare,","185-5012 Rhoncus Av.",51,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (19,"netus","Ap #530-3040 Felis St.",55,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (20,"ut","Ap #289-9138 Arcu Rd.",39,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (21,"elit","Ap #738-4447 Purus, Rd.",50,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (22,"aliquam","748-5120 Eu Avenue",56,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (23,"Mauris","P.O. Box 745, 2185 Aenean Rd.",31,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (24,"arcu.","535-6285 Suspendisse Av.",26,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (25,"Sed","871-8929 Ultrices Ave",21,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (26,"sollicitudin","P.O. Box 655, 8794 Hendrerit Road",53,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (27,"aliquet","P.O. Box 609, 4463 Venenatis Rd.",16,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (28,"quis","347-8204 Ligula Road",12,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (29,"amet","199-8503 Malesuada Street",20,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (30,"tellus","Ap #397-7194 Ligula Road",16,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (31,"tempor","P.O. Box 534, 4584 Rutrum Rd.",57,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (32,"vel","9702 Gravida Avenue",51,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (33,"feugiat","P.O. Box 618, 9650 Odio. Road",17,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (34,"metus.","121-1768 Ultrices. Rd.",30,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (35,"cursus","Ap #882-2422 Egestas, Rd.",30,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (36,"in","458-9723 Posuere Street",12,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (37,"lacus.","268-2812 Aenean Street",57,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (38,"ullamcorper","186-2080 Massa. St.",50,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (39,"Nullam","Ap #818-9288 Vestibulum Avenue",59,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (40,"Nunc","213-2223 Ipsum Avenue",39,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (41,"pharetra,","1089 Nisi Av.",36,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (42,"nisi","7431 Justo Av.",36,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (43,"tempor,","374-2219 Amet Rd.",24,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (44,"nibh","1729 Sagittis Street",51,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (45,"vitae","899-3036 Egestas Ave",34,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (46,"gravida","P.O. Box 807, 9708 Luctus Rd.",50,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (47,"commodo","P.O. Box 711, 5570 Integer St.",38,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (48,"ut","P.O. Box 729, 9813 At Road",20,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (49,"tortor.","P.O. Box 834, 3961 Ultrices. St.",30,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (50,"lacus.","P.O. Box 849, 3277 Mattis Rd.",19,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (51,"Ut","372-347 Egestas, Rd.",26,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (52,"feugiat","P.O. Box 973, 2765 Augue Avenue",36,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (53,"nisi","104-4579 Lacus. St.",29,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (54,"lorem","Ap #689-1369 Ac Road",43,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (55,"sagittis.","5413 Aliquam Rd.",43,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (56,"nunc","Ap #105-8549 Quam. Road",18,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (57,"gravida","Ap #228-6918 Imperdiet St.",20,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (58,"Quisque","Ap #430-6174 Mauris Road",56,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (59,"arcu","974-2888 Est Road",18,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (60,"diam","Ap #220-8066 Cras Avenue",16,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (61,"malesuada","3028 Donec Ave",56,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (62,"tortor","P.O. Box 629, 5538 Sed Ave",58,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (63,"pede,","561-822 Orci. Street",31,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (64,"mi","491-5764 Gravida Ave",35,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (65,"feugiat","P.O. Box 582, 5307 Aliquam Rd.",39,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (66,"metus.","Ap #784-4263 Cursus. Ave",37,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (67,"diam.","Ap #998-4846 Dictum St.",40,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (68,"vitae,","1465 Non, Rd.",58,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (69,"scelerisque","P.O. Box 452, 291 Augue. St.",58,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (70,"eu","831 Pede. Road",24,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (71,"mauris,","267-8774 Vivamus St.",55,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (72,"vitae,","991-4858 Convallis Road",35,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (73,"et","509-2991 Augue Street",23,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (74,"luctus","478-1585 Ridiculus St.",31,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (75,"dis","4351 Egestas. Avenue",35,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (76,"posuere,","119-6624 Vitae St.",46,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (77,"Ut","P.O. Box 101, 9747 Mollis Avenue",19,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (78,"Duis","P.O. Box 514, 1282 Lobortis Rd.",27,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (79,"cursus","9803 Mauris Av.",32,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (80,"scelerisque","5373 Eget, St.",37,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (81,"tellus.","P.O. Box 522, 9660 Suspendisse Rd.",29,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (82,"aliquam","491-2498 Nullam St.",49,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (83,"hendrerit","P.O. Box 432, 164 Tincidunt Rd.",23,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (84,"nunc.","4915 Interdum. Road",28,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (85,"vitae","9637 Mauris Ave",50,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (86,"posuere","403-2646 Vehicula Road",28,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (87,"cursus","Ap #244-803 Enim. St.",16,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (88,"tincidunt","Ap #944-2002 Cum St.",55,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (89,"imperdiet","P.O. Box 357, 3194 In Av.",10,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (90,"amet,","Ap #916-9743 Mi Road",46,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (91,"lectus","2684 Velit St.",42,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (92,"luctus","Ap #567-482 Sed Rd.",18,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (93,"massa.","6212 Blandit. Ave",53,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (94,"urna.","705-3220 Sagittis Av.",19,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (95,"lectus","P.O. Box 552, 2104 A, Ave",29,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (96,"rutrum,","P.O. Box 677, 4152 Amet, Road",34,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (97,"vel","P.O. Box 473, 4005 Sed, Road",23,"AULA_CAPACITACION");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (98,"eu,","795-5567 Mauris Ave",21,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (99,"augue","P.O. Box 582, 5634 Orci St.",50,"SUCURSAL");
INSERT INTO aulas (id_aula,descripcion,direccion,capacidad,tipo) VALUES (100,"lobortis","Ap #861-5741 Proin Street",17,"SUCURSAL");


-- EMPLEADOS
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (1,"EMPLEADO","1641070770199","Evangeline","Warren","Nulla.tincidunt.neque@Integer.org",16);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (2,"EMPLEADO","1692082974299","Katell","Joyner","id.sapien.Cras@magnaPraesent.org",8);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (3,"EMPLEADO","1683080353199","Amery","Duncan","Vivamus.nisi.Mauris@penatibuset.com",84);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (4,"ENTRENADOR","1633121305199","Yvonne","Watts","Nunc.quis.arcu@nibhAliquamornare.edu",31);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (5,"EMPLEADO","1621081230999","Nathaniel","Montoya","nec.imperdiet@pretium.edu",25);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (6,"EMPLEADO","1635112415199","Brett","Avery","Mauris@Ut.ca",72);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (7,"EMPLEADO","1617062545999","Damon","Hernandez","molestie@elitCurabitur.edu",3);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (8,"ENTRENADOR","1675082479599","Uta","Collier","placerat@ipsumdolorsit.co.uk",87);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (9,"EMPLEADO","1603050851799","Porter","Olson","sagittis.Duis@tellussem.org",61);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (10,"ENTRENADOR","1604022271499","Jade","Park","justo@variusultrices.co.uk",46);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (11,"ENTRENADOR","1600082809799","Caesar","Santos","arcu@tellusjustosit.com",84);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (12,"EMPLEADO","1654031786199","Keiko","Blair","luctus.et.ultrices@nullaat.com",84);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (13,"ENTRENADOR","1623051954699","Hilary","Coffey","Nulla.tempor.augue@elementumat.org",40);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (14,"ENTRENADOR","1627012600099","Audra","Jenkins","lectus.a@duiSuspendisse.com",42);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (15,"EMPLEADO","1638010751699","Sylvia","Hall","Etiam.laoreet@nullaCras.com",29);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (16,"ENTRENADOR","1663081168199","Melyssa","Dunn","hendrerit.consectetuer.cursus@sitamet.edu",6);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (17,"ENTRENADOR","1606111205299","Lacy","Hawkins","libero.Proin@Curabiturmassa.ca",73);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (18,"ENTRENADOR","1643102393399","Igor","Morin","varius.Nam.porttitor@magna.org",39);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (19,"EMPLEADO","1662062193799","Porter","Cherry","augue.eu.tellus@pedenonummyut.ca",96);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (20,"EMPLEADO","1640072683499","India","Browning","Morbi@Curabiturconsequat.com",8);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (21,"EMPLEADO","1666010785199","Hunter","Clark","eu.sem.Pellentesque@ultriciesligula.ca",57);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (22,"EMPLEADO","1692011483099","Rooney","Mayo","in@MaurismagnaDuis.net",75);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (23,"EMPLEADO","1664080696599","Mari","Schneider","In.ornare@mauriserateget.ca",43);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (24,"ENTRENADOR","1668030326399","Maryam","Conway","consectetuer@ipsumprimisin.co.uk",95);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (25,"EMPLEADO","1602031675999","Garth","Burns","cursus.Integer.mollis@estmollisnon.net",49);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (26,"EMPLEADO","1638112797199","Belle","Schultz","neque@hendreritaarcu.co.uk",63);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (27,"ENTRENADOR","1604090959599","Aurora","Obrien","ligula@Proin.co.uk",99);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (28,"ENTRENADOR","1694111225599","Mikayla","Mcdowell","Class.aptent@imperdietullamcorperDuis.org",95);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (29,"EMPLEADO","1609082525399","Justin","Myers","lobortis@elitAliquam.com",12);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (30,"EMPLEADO","1674062234599","Liberty","Lane","sem.vitae.aliquam@velesttempor.ca",55);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (31,"EMPLEADO","1698010715799","Galvin","Sykes","metus@magnaLorem.ca",27);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (32,"EMPLEADO","1693030271099","Ocean","Estes","nibh@sapienNuncpulvinar.ca",16);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (33,"ENTRENADOR","1605030805699","Bruce","Frank","Sed.dictum@turpisNulla.org",62);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (34,"EMPLEADO","1646112816399","Quyn","Head","semper@sit.ca",50);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (35,"ENTRENADOR","1666082582299","Freya","Bradford","et@egestasnunc.edu",75);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (36,"ENTRENADOR","1675052337999","Cherokee","Jennings","diam@lacus.co.uk",42);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (37,"ENTRENADOR","1671091195999","Kylie","West","mauris.erat@laciniaatiaculis.com",98);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (38,"ENTRENADOR","1665042541099","Wyoming","Boone","Etiam.imperdiet.dictum@magnisdisparturient.ca",15);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (39,"ENTRENADOR","1627081448899","Allen","Hatfield","montes.nascetur.ridiculus@arcuSed.com",100);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (40,"EMPLEADO","1631121622999","Jelani","Abbott","arcu.eu@lobortisnisi.org",62);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (41,"EMPLEADO","1616011597199","Micah","Bernard","Proin@faucibusleo.com",31);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (42,"ENTRENADOR","1624030775599","Oren","Dillard","eu.odio@Maurismolestiepharetra.edu",56);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (43,"EMPLEADO","1622020786199","Nichole","Tyson","pede.sagittis@urna.com",89);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (44,"ENTRENADOR","1682012242199","Harriet","Kent","dolor.dapibus.gravida@quam.net",31);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (45,"ENTRENADOR","1652052895399","Kamal","Horne","ligula@Maurisut.org",52);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (46,"EMPLEADO","1609051273899","Basia","Andrews","In.scelerisque@idblanditat.com",81);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (47,"EMPLEADO","1612060734099","Julian","Diaz","amet.metus.Aliquam@mipedenonummy.ca",47);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (48,"ENTRENADOR","1607083044899","Montana","Battle","sit.amet@enimconsequatpurus.net",70);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (49,"EMPLEADO","1683052591099","September","Carr","ac@convallisest.co.uk",59);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (50,"EMPLEADO","1624012187599","Cassady","Battle","Donec.dignissim.magna@dignissim.com",34);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (51,"EMPLEADO","1664120490699","Iliana","Cunningham","consequat@gravida.edu",8);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (52,"EMPLEADO","1686041322599","Graham","Carlson","lobortis.nisi.nibh@tincidunt.org",70);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (53,"ENTRENADOR","1623120420599","Tallulah","Vance","Donec.at.arcu@ut.co.uk",38);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (54,"EMPLEADO","1664091489899","Helen","Wilkinson","Lorem.ipsum@vestibulumneque.org",56);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (55,"EMPLEADO","1626110365899","Rhoda","Hurley","lectus.convallis@fringillapurus.net",77);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (56,"EMPLEADO","1615021956199","Karly","Barlow","non.lacinia@eratvolutpatNulla.com",22);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (57,"ENTRENADOR","1663052322699","Jamal","Hahn","sed.tortor.Integer@elit.com",70);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (58,"ENTRENADOR","1689080244999","Ingrid","David","Curabitur@tellusloremeu.edu",55);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (59,"ENTRENADOR","1662020599299","Rudyard","Hatfield","diam@dictumPhasellus.com",58);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (60,"ENTRENADOR","1646052709099","Ima","Callahan","eu.dolor.egestas@ullamcorper.edu",49);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (61,"EMPLEADO","1643040428999","Tucker","Landry","elit@iaculisnec.net",58);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (62,"ENTRENADOR","1635111065499","Elaine","Dennis","id@ac.co.uk",88);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (63,"ENTRENADOR","1650091481099","Avye","Hampton","mus@sedleo.net",20);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (64,"ENTRENADOR","1683071101299","Roanna","Matthews","magna@pharetra.com",25);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (65,"EMPLEADO","1675050191599","Daphne","Anthony","Suspendisse.tristique.neque@velesttempor.com",22);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (66,"EMPLEADO","1641062034099","Vincent","Strong","Fusce@fermentum.edu",40);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (67,"EMPLEADO","1645120527399","Daniel","Mccullough","aliquam.adipiscing.lacus@idante.com",69);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (68,"EMPLEADO","1677012946199","Kimberly","Pruitt","dapibus.id.blandit@egetodioAliquam.net",66);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (69,"EMPLEADO","1668041561699","Odysseus","Pratt","mi@primis.edu",31);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (70,"EMPLEADO","1698092156699","Wade","Compton","diam@sodalesatvelit.ca",74);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (71,"ENTRENADOR","1602051852299","Jakeem","Adams","ligula.Nullam@Aliquam.ca",38);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (72,"ENTRENADOR","1697062546199","Wynne","Sweet","nec.urna@pretium.net",27);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (73,"ENTRENADOR","1688101310499","Marsden","Murray","scelerisque.neque.sed@felisullamcorperviverra.co.uk",87);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (74,"ENTRENADOR","1672121139499","Dacey","Case","Nunc.commodo.auctor@duiCum.com",43);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (75,"ENTRENADOR","1662031536699","Madonna","Gamble","elementum.at@nec.net",58);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (76,"ENTRENADOR","1694051938399","Xanthus","Glass","nibh@neque.ca",85);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (77,"EMPLEADO","1635091259399","Jael","Kim","tristique.pharetra@variusultrices.co.uk",17);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (78,"ENTRENADOR","1681031332299","Mallory","Guzman","bibendum.Donec@Sed.edu",40);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (79,"EMPLEADO","1668020703499","Odette","Bolton","blandit@sed.net",79);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (80,"EMPLEADO","1601011096899","Hamilton","Dominguez","purus@aarcuSed.com",74);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (81,"ENTRENADOR","1689030704299","Raya","Maynard","scelerisque.scelerisque@dolorFuscemi.com",31);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (82,"EMPLEADO","1618040823499","Silas","Mayer","eget@ut.net",42);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (83,"EMPLEADO","1663061921299","Shaine","Martin","nec@ligula.edu",86);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (84,"EMPLEADO","1608070497899","Scott","Yang","ipsum@fermentumvelmauris.org",70);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (85,"ENTRENADOR","1649090631999","Teegan","Castro","in@tinciduntpede.ca",90);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (86,"ENTRENADOR","1662060485699","Kelsey","Gill","fringilla@vestibulum.net",37);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (87,"ENTRENADOR","1671102595599","Winter","Jordan","non.nisi@mattisIntegereu.ca",66);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (88,"EMPLEADO","1646081108299","Candice","Ross","Donec.dignissim.magna@at.org",20);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (89,"EMPLEADO","1679040762999","Maxwell","Obrien","nec.quam@justo.org",39);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (90,"EMPLEADO","1698081094999","Priscilla","Mann","orci@sollicitudin.org",5);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (91,"EMPLEADO","1641110150099","Doris","Young","elit@felisDonectempor.edu",85);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (92,"ENTRENADOR","1658092569999","Wylie","Mcguire","Proin.dolor.Nulla@dis.com",64);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (93,"ENTRENADOR","1664072719099","Orlando","Jones","orci.luctus@diam.org",96);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (94,"EMPLEADO","1648022680399","Marny","Duke","Quisque.tincidunt@faucibus.co.uk",85);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (95,"EMPLEADO","1642051347899","Judah","Fry","diam.dictum@tinciduntnibhPhasellus.com",69);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (96,"EMPLEADO","1690012926899","Lance","Combs","Cum.sociis.natoque@Phasellusornare.ca",98);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (97,"ENTRENADOR","1657052414999","Alan","Good","faucibus.lectus@sem.com",67);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (98,"ENTRENADOR","1653070345099","Martha","Sullivan","Morbi@disparturient.com",38);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (99,"ENTRENADOR","1668110983499","Baker","Maddox","Maecenas.iaculis.aliquet@lectusrutrumurna.co.uk",46);
INSERT INTO empleados (id_empleado,tipo,dni,nombre,apellido,email,nroSucursal) VALUES (100,"ENTRENADOR","1603072014799","Plato","Pugh","orci.in@non.com",69);


-- CURSOS
insert into cursos values(1, 'Orientacion', 'Reune las clases necesarias para darle una orientacion general al nuevo empleado acerca de la empresa');
insert into cursos values(2, 'Introduccion Starbucks', 'Reune las clases necesarias para darle una orientacion general al nuevo empleado acerca de Starbucks');
insert into cursos values(3, 'El Café, materia prima', 'Reune las clases necesarias para darle una orientacion general al nuevo empleado acerca de la materia prima que se trabaja en Starbucks, que es el Cafe en todas sus variantes y origenes');
insert into cursos values(4, 'Relacion con el cliente', 'Reune las clases necesarias para darle una orientacion general al nuevo empleado acerca de la relacion con el cliente.');
insert into cursos values(5, 'Certificacion Barista', 'Reune las clases necesarias para ser certificado como Barista');


-- CLASES
insert into clases values(1, "Alsea S.A introducción", 1);
insert into clases values(2, 'Como manejarse dentro de la organización', 1);
insert into clases values(3, "Licencias en general", 1);
insert into clases values(4, 'Beneficios!', 1);
insert into clases values(5, 'Bienvenido a Starbucks!', 2);
insert into clases values(6, 'La empresa y su visión', 2);
insert into clases values(7, 'Planes de carrera', 2);
insert into clases values(8, 'Historia del café', 3);
insert into clases values(9, 'Geografía del café', 3);
insert into clases values(10, 'Reconociendo olores', 3);
insert into clases values(11, 'Principios de preparación', 3);
insert into clases values(12, 'El cliente, nuestra prioridad', 4);
insert into clases values(13, 'Formas de referirse al cliente', 4);
insert into clases values(14, 'Problemas habituales y como accionar', 4);
insert into clases values(15, 'Como preparar café', 5);
insert into clases values(16, 'Exámen cerficador', 5);

-- CERTIFICACIONES

insert into certificaciones values(1, 10, 1);
insert into certificaciones values(2, 13, 2);
insert into certificaciones values(3, 27, 3);
insert into certificaciones values(4, 44, 4);
